/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

#ifndef MENU_GENERATED_CODE_H
#define MENU_GENERATED_CODE_H

#include <PlatformDetermination.h>
#include <tcMenu.h>


#include <tcMenuBuilder.h>
#include "FrameBufferDrawable.h"
#include "stmCubeTouchBsp.h"
#include <extras/DrawableTouchCalibrator.h>
#include <tcUnicodeHelper.h>
#include <IoAbstraction.h>
#include <EepromItemStorage.h>
#include <mbed/HalStm32EepromAbstraction.h>

// variables we declare that you may need to access
extern const PROGMEM ConnectorLocalInfo applicationInfo;
extern StmDMA2dAdafruitFrameBuffer16 gfx;
extern TcAdafruitFrameDrawable gfxDrawable;
extern GraphicsDeviceRenderer renderer;
extern StBspTouchInterrogator touchInterrogator;
extern iotouch::TouchOrientationSettings touchSettings;
extern MenuTouchScreenManager touchScreenManager;
extern tcextras::IoaTouchScreenCalibrator touchCal;
extern const UnicodeFont RobotoRegular16pt[];
extern const UnicodeFont RobotoMedium24[];

// Any externals needed by IO expanders, EEPROMs etc


// Forward define the menu builder function
void buildMenu(TcMenuBuilder& builder);

// The following defines all menu item IDs.
#define MENU_LINE_VOLTS_ID  6
#define MENU_STATUS_ID  7
#define MENU_COUNT_ID  4
#define MENU_ADD_ID  5

// Inline helper methods to access menu items
inline AnalogMenuItem& getMenuLineVolts() { return getAnalogItemById(MENU_LINE_VOLTS_ID); }
inline EnumMenuItem& getMenuStatus() { return getEnumItemById(MENU_STATUS_ID); }
inline AnalogMenuItem& getMenuCount() { return getAnalogItemById(MENU_COUNT_ID); }
inline ActionMenuItem& getMenuAdd() { return getActionItemById(MENU_ADD_ID); }


// Provide a wrapper to get hold of the root menu item and export setupMenu
inline MenuItem& rootMenuItem() { return getMenuLineVolts(); }
void setupMenu();

// Callback functions must always include CALLBACK_FUNCTION after the return type
#define CALLBACK_FUNCTION

void CALLBACK_FUNCTION tcAdded_onAddToCount(int id);

#endif // MENU_GENERATED_CODE_H
