/*
The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
 */

// Generated for PicoSDK/STMCube CMake by TcMenu 4.6.0-SNAPSHOT on 2026-08-23T10:02:26.895849Z.

#include <tcMenu.h>
#include "TestLTDC_menu.h"

// Each plugin's code now follows here

#include <Fonts/RobotoRegular16pt.h>
#include <Fonts/RobotoMedium24.h>
#include "IceWhiteModernTheme.h"

// Global variable declarations
const  ConnectorLocalInfo applicationInfo = { "Test LTDC", "5d8a2000-bbd4-4e77-8991-f4417456fec7" };
HalStm32EepromAbstraction glBspRom;
StmDMA2dAdafruitFrameBuffer16 gfx((uint16_t*)0xD0000000, 240, 320);
TcAdafruitFrameDrawable gfxDrawable(&gfx);
GraphicsDeviceRenderer renderer(64, applicationInfo.name, &gfxDrawable);
StBspTouchInterrogator touchInterrogator(240, 320);
iotouch::TouchOrientationSettings touchSettings(false, false, false);
MenuTouchScreenManager touchScreenManager(&touchInterrogator, &renderer, touchSettings);
tcextras::IoaTouchScreenCalibrator touchCal(&touchScreenManager, &renderer, 256);

void setupMenu() {
    // First we set up eeprom and authentication (if needed).
    setEepromStorageMode(TC_STORE_ROM_DYNAMIC);
    glBspRom.initialise(0);
    menuMgr.setEepromRef(&glBspRom);
    TcMenuBuilder builder = TcMenuBuilder(&MenuManager::ROOT);
    buildMenu(builder);

    // Code generated by plugins and new operators.
        gfx.setRotation(0);
        gfx.init(true);
        gfx.setRotation(0);
        renderer.setUpdatesPerSecond(10);
        touchInterrogator.init();
        menuMgr.initWithoutInput(&renderer, &getMenuLineVolts());
        touchScreenManager.start();
        applyTheme(renderer);
}

